name: Node.js push on develop branch

on:
  push:
    branches: [develop]

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-18.04
    # Run the steps in a Docker container on the virtual machine
    container:
      image: node:12.16.2
    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

      # Install the dependencies needed for the project
      - name: Install dependencies
        run: npm ci
      # Build the project
      - name: Build
        run: npm run build --if-present
      # Test the project
      - name: Test
        run: npm test
        env:
          CI: true
      # Upload the release folder and Dockerfile artifacts to this GitHub workflow for use in the next job
      - name: Upload release artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-artifact
          path: ./dist
      - name: Upload Dockerfile artifact
        uses: actions/upload-artifact@v1
        with:
          name: dockerfile-artifact
          path: ./Dockerfile
      - name: Upload kubernetes artifact
        uses: actions/upload-artifact@v1
        with:
          name: kubernetes-artifact
          path: ./kube_develop
  deliver:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      # Download artifacts from GitHub workflow to use in this job
      - name: Download release artifact
        uses: actions/download-artifact@v1
        with:
          name: release-artifact
          path: ./build
      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v1
        with:
          name: dockerfile-artifact
          path: .
      # Deliver Docker image to Github packages
      - name: Deliver Docker image
        env:
          CONTAINER_IMAGE: docker.pkg.github.com/kwetters6/frontend/frontend:${{ github.sha }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}"| docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t $CONTAINER_IMAGE .
          docker push $CONTAINER_IMAGE
  deploy:
    needs: deliver
    runs-on: ubuntu-18.04
    steps:
      - name: Download kubernetes artifact
        uses: actions/download-artifact@v1
        with:
          name: kubernetes-artifact
          path: ./kube_develop

      - uses: Azure/setup-kubectl@v1

      - uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: Azure/k8s-create-secret@v1
        with:
          namespace: kwetter-development
          container-registry-url: docker.pkg.github.com
          container-registry-username: ${{ secrets.DOCKER_USER }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          secret-name: github-docker-registry

      - uses: Azure/k8s-deploy@v1
        with:
          namespace: kwetter-development
          manifests: |
            ./kube_develop/kube_deployment.yaml
            ./kube_develop/kube_service.yaml
            
          images: |
            docker.pkg.github.com/kwetters6/frontend/frontend:${{ github.sha }}
          imagepullsecrets:
            github-docker-registry